version: '2'

services:
  web1:
    restart: always
    build: ./web1
    expose:
      - "8000"
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  web2:
    restart: always
    build: ./web2
    expose:
      - "8000"
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web1:web1
      - web2:web2
      